"""
Diagnose fingering quality: identify potential sources of low accuracy.

Checks:
1. Frame alignment: our tokenlist (onset*60) vs keyhandlist frame range
2. Note order: MIDI note order consistency
3. Noinfo distribution: which notes fail
4. Error pattern: hand wrong vs finger wrong
"""
import json
import os
import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _SCRIPT_DIR.parent.parent
sys.path.insert(0, str(_SCRIPT_DIR))
import config

# Load GT
import importlib.util
_fingergt_path = _PROJECT_ROOT / "FingeringDetection" / "detection" / "fingergt.py"
_spec = importlib.util.spec_from_file_location("fingergt", str(_fingergt_path))
_fingergt = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_fingergt)
GT_MAP = _fingergt.GT_MAP


def from_internal(v):
    if v <= 5:
        return ("L", v)
    return ("R", v - 5)


def parse_pred(note):
    hand, finger = note.get("hand"), note.get("finger")
    if hand and finger and finger != "Noinfo" and isinstance(finger, int) and 1 <= finger <= 5:
        return (hand, finger)
    if finger is None or finger == "Noinfo":
        return (None, None)
    if isinstance(finger, int) and 1 <= finger <= 10:
        return from_internal(finger)
    return (None, None)


def diagnose_one(basename, pred_path, gt_list):
    if not os.path.exists(pred_path):
        return None
    with open(pred_path) as f:
        data = json.load(f)
    notes = data.get("notes", [])
    n_gt = len(gt_list)
    if len(notes) < n_gt:
        return None

    hand_wrong = 0
    finger_wrong = 0
    exact_ok = 0
    noinfo = 0
    errors = []

    for i in range(n_gt):
        gt_h, gt_f = gt_list[i]
        pred_h, pred_f = parse_pred(notes[i])
        if pred_h is None:
            noinfo += 1
            continue
        if pred_h == gt_h and pred_f == gt_f:
            exact_ok += 1
        else:
            if pred_h != gt_h:
                hand_wrong += 1
                errors.append((i, "hand", gt_h, pred_h, gt_f, pred_f))
            else:
                finger_wrong += 1
                errors.append((i, "finger", gt_h, pred_h, gt_f, pred_f))

    return {
        "basename": basename,
        "n": n_gt,
        "noinfo": noinfo,
        "exact_ok": exact_ok,
        "hand_wrong": hand_wrong,
        "finger_wrong": finger_wrong,
        "eval_n": n_gt - noinfo,
        "errors": errors[:20],
    }


def main():
    input_dir = config.OUTPUT_DIR
    if not os.path.exists(input_dir):
        print(f"Error: {input_dir} not found")
        sys.exit(1)

    print("=" * 60)
    print("Fingering Quality Diagnosis")
    print("=" * 60)

    total_hand_wrong = 0
    total_finger_wrong = 0
    total_eval = 0

    for basename, gt_list in sorted(GT_MAP.items()):
        pred_path = os.path.join(input_dir, basename + ".json")
        d = diagnose_one(basename, pred_path, gt_list)
        if d is None:
            print(f"\n[SKIP] {basename}")
            continue

        total_hand_wrong += d["hand_wrong"]
        total_finger_wrong += d["finger_wrong"]
        total_eval += d["eval_n"]

        print(f"\n--- {basename} ---")
        print(f"  Evaluable: {d['eval_n']}, Noinfo: {d['noinfo']}")
        print(f"  Exact OK: {d['exact_ok']} ({100*d['exact_ok']/d['eval_n']:.1f}%)")
        print(f"  Hand wrong: {d['hand_wrong']} ({100*d['hand_wrong']/d['eval_n']:.1f}%)")
        print(f"  Finger wrong (hand OK): {d['finger_wrong']} ({100*d['finger_wrong']/d['eval_n']:.1f}%)")

        if d["errors"]:
            print(f"  Sample errors (first 5):")
            for i, err_type, gh, ph, gf, pf in d["errors"][:5]:
                print(f"    note {i}: {err_type} | GT {gh}{gf} pred {ph}{pf}")

    print("\n" + "=" * 60)
    print("Summary")
    print("=" * 60)
    if total_eval > 0:
        print(f"  Hand errors: {total_hand_wrong} ({100*total_hand_wrong/total_eval:.1f}%)")
        print(f"  Finger errors (hand correct): {total_finger_wrong} ({100*total_finger_wrong/total_eval:.1f}%)")
    print("\nPotential causes of low quality:")
    print("  1. Frame alignment: Our export uses onset*60 fps. Keyhandlist was built with")
    print("     miditotoken (beat-based). Tempo mismatch or different MIDI can cause drift.")
    print("  2. MIDI difference: ASDF uses _singletempo MIDI from midiconvert. We use")
    print("     PianoVAM_v1.0/MIDI/*.mid. Different files = different note order/timing.")
    print("  3. Keyhandlist source: fingering_*.pkl was generated by ASDF handfingercorresponder.")
    print("     Hand detection noise or keyboard calibration affects quality.")
    print("  4. Decider thresholds: 0.5 (min) and 0.8 (high) for finger score. May need tuning.")


if __name__ == "__main__":
    main()
